### ISSUE TITLE
Reshape library interferes with ObservedStatsUSGS

### ISSUE THREAD

**Issue by aditibhaskar** [USGS-R/EflowStats#17]
The following works fine (modified from the example in the PDF): 

```{r}
library(EflowStats)
ObservedStatsUSGS("02177000",2009,2013,"magnifSeven")
```
But this does not work: 
```{r}
library(EflowStats)
library(reshape)
ObservedStatsUSGS("02177000",2009,2013,"magnifSeven")
```
And gives the following error message: 
```{r}
Error in aggregate.data.frame(mf[1L], mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate
In addition: Warning message:
In `[<-.factor`(`*tmp*`, ri, value = c(889, 825, 787, 718, 919,  :
  invalid factor level, NA generated
```
To get around this right now, I am loading the reshape library after the stats have been generated.

**Comment by dblodgett-usgs** [comment]
Thanks for the report, we'll take a look and see about fixing this.

**Comment by tmills-usgs** [comment]
Another workaroud:

the reshape2 library does not cause the error. If the function you need is available in the reshape2 library you could use that instead.

**Comment by ldecicco-USGS** [comment]
This is taking me a surprisingly long time to fix. There's clearly a namespace conflict because both reshape and reshape2 have the melt function. I'm surprised just prefacing the call with `reshape2::melt` can't work. It's discussed a bit here:

http://stackoverflow.com/questions/16896632/reshape-package-masking-preventing-melt-from-naming-columns

To tack on to @tmills-usgs 's comment, if possible...use the reshape2 package whenever possible. A newer package if you want to skip ahead is `tidyr`. 

That being said, with the 2 reshaping calls, I've been able to get one to work (no matter if reshape is loaded or not), and I'm working on the second call. Once that's done, I'll push out a new release of dataRetrieval.

**Comment by aditibhaskar** [comment]
Thank you for the update and workaround using reshape2.

On Mon, Jun 15, 2015 at 5:45 PM, Laura DeCicco <notifications@github.com>
wrote:

> This is taking me a surprisingly long time to fix. There's clearly a
> namespace conflict because both reshape and reshape2 have the melt
> function. I'm surprised just prefacing the call with reshape2::melt can't
> work. It's discussed a bit here:
>
>
> http://stackoverflow.com/questions/16896632/reshape-package-masking-preventing-melt-from-naming-columns
>
> To tack on to @tmills-usgs <https://github.com/tmills-usgs> 's comment,
> if possible...use the reshape2 package whenever possible. A newer package
> if you want to skip ahead is tidyr.
>
> That being said, with the 2 reshaping calls, I've been able to get one to
> work (no matter if reshape is loaded or not), and I'm working on the second
> call. Once that's done, I'll push out a new release of dataRetrieval.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/EflowStats/issues/17#issuecomment-112220095>.
>



-- 
Aditi S. Bhaskar
NSF Postdoctoral Research Fellow
U.S. Geological Survey, Eastern Geographic Science Center
12201 Sunrise Valley Drive, MSN 521, Reston, VA 20192
Phone: (703) 648-5157
http://aditibhaskar.weebly.com/
