### ISSUE TITLE
characterization testing

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#18]
The example from each statistic function needs to be in testthat format with the value that's currently returned should be expected in the test. These should probably be broken up according to the package organization but follow the pattern that's been started here: https://github.com/USGS-R/EflowStats/blob/master/tests/testthat/statTests.R

**Comment by tmills-usgs** [comment]
I have begun this process and have changed the organization slightly. I am organizing as follows:

testthat files are broken out by function type as described in the package vignette tables, e.g. "magnitude functions". Within each file is a separate test_that for each function, rather than grouping multiple functions inside a test_that chunk. This allows for explicit warnings about the specific function failing.

see github.com/tmills-usgs/EflowStats/tree/master/tests/testthat/magnitudeFunctionTests.R for an example.

**Comment by dblodgett-usgs** [comment]
@tmills-usgs Looks like you've gotten to working on this, don't forget that we need to get the travis tests working.

**Comment by tmills-usgs** [comment]
Yeah I got a bit done, I will start working on writing more testThat tests. I will also try to get the travis stuff up and running, but if I am just spinning my wheels I will wait until I visit Middleton in Nov. and try and get a little hand-holding on it from some of the CIDA folks
