### ISSUE TITLE
Ability to define water year other than Oct-Oct

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#22]
This is a desired enhancement. Currently, only October based water years can be used. Some users would like to be able to specify a different month as the first month of the water year.

**Comment by tmills-usgs** [comment]
This is possible, most likely with a change to get_obsdata(). However, it is liekly going to be a fairly large change.

**Comment by dblodgett-usgs** [comment]
Going to close this stale old ticket. We've got calendar and water. We need to do a big picture look at what might be needed in this and other packages before we jump into stuff like this.

**Comment by jenskiesel** [comment]
I think having this functionality would be awesome - especially for using the package elsewhere (in Europe our water year mostly starts in November and in other climate regions / southern hemisphere it is completely different). I had a look at the code and I thought it is 'only' 
        get_waterYear.R
        get_waterYearDay.R
that need to receive the month as a variable and then all other functions need to pass the month to
        validate_data.R
The variable can be set to a default of "10L" so users can use it if they want but do not need to make changes to their code calling the EflowStats package if they don't.

I suspect I may be missing something (considering the last post from @dblodgett-usgs), but I just tried this now. Sorry in advance, I have no experience contributing to R packages. I downloaded the .zip and made local changes to the code. I followed this logic in calculating the waterYearDay:

The day of the year after the beginning of the water year can be calculated by subtracting dates:
- if the current date is before the current water year date:
   year_day is the days between current date and the previous water year + 1 day
- else (current date is after the current water year date):
   year_day is the days between current date and the actual water year + 1 day

My code implementation is then:

        get_waterYearDay <- function(x, wyMonth) {    
        doy <- lubridate::yday(x)  # day of year series
        year <- as.integer(lubridate::year(x))  # actual year series - this must be integer for the subtraction
        pyear <- year-1  # previous year series
        wy_date <- as.Date(paste(year,wyMonth,"01", sep = "-"))  # series with the date of the water year in the current year
        pwy_date <- as.Date(paste(pyear,wyMonth,"01", sep = "-"))  # series with the date of the water year in the previous year
        year_day <- ifelse(wy_date > x, x-pwy_date+1, x-wy_date+1)
        return(year_day)
        }

The function returns the same series as the original one for wyMonth=10, however, I can't test my changes in the package because if I install my local .zip with:

        install.packages(file.choose(), repos = NULL, type="source")


on loading the package I get the error (same error if I use the original .zip I downloaded from your repo):

        > library(EflowStats)
        Error in library(EflowStats) :
        ‘EflowStats’ is not a valid installed package

This may be worth opening a separate issue (I could not find an issue dealing with this), but maybe I am missing something obvious and you could quickly point me to the right direction why the local install from source does not work? I am happy to do further testing of my changes then.

**Comment by dblodgett-usgs** [comment]
Hi -- Thanks for thinking about a contribution @jenskiesel.

I would start here: https://r-pkgs.org/ to learn more about contributing to packages. You will likely need to learn a bit of git to pull down the source code and make contributions -- probably start here: https://docs.github.com/en/get-started/quickstart/set-up-git for that.

**Comment by jenskiesel** [comment]
Thanks @dblodgett-usgs for the suggestions!

I hope I followed the correct procedure now:
- forked the EflowStats package
- changed the functions
- re-run "devtools::document()"
- commited and pushed to the forked package
- created a pull request

I installed the 'new' package and ran a few tests - all seems to work as expected but I did not conduct a thorough comparison with the 'original' package. Do you have some standardized tests that can quickly be run for new contributions?
