### ISSUE TITLE
Improve documentation of qfiletempf dataframe

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/EflowStats#46]
The required columns are not listed in the documentation for qfiletempf.

For example in, dh17, and I think most functions, requires a wy_val column which is not specified in the documentation.

**Comment by jasonelaw** [comment]
This a symptom of the code making assumptions about the data being passed that aren't validated. I find that it is much easier and less bug prone to explicitly pass vectors rather than a single data.frame to code that makes assumptions about the data. The dh* and dl* functions really only require the discharge time series, including the date and they could look like:
```
dh2 <- function(discharge, date, pref = "mean"){...}
# OR
dh2 <- function(ts, pref = "mean"){...}
# where ts is something like a zoo object:
ts <- zoo(discharge, order.by = date)
```
In this way, the requirements are explicit and no one needs to rename a data.frame just to call your code.
