### ISSUE TITLE
Biased calculations for dh* and dl*

### ISSUE THREAD

**Issue by jasonelaw** [USGS-R/EflowStats#61]
Most of the dl\* and dh\* functions rely on code like this:

```
    for (i in 1:noyrs) {
        subsetyr <- subset(qfiletempf, as.numeric(qfiletempf$wy_val) == 
            noyears$Year[i])
        day3mean <- rollmean(subsetyr$discharge, 3, align = "right", 
            na.pad = TRUE)
        max3daybyyear[i] <- max(day3mean, na.rm = TRUE)
    }
```

Subsetting the data by years before taking the rolling average doesn't really make any sense. Hydrologically, the year boundary is arbitrary. However the effect of this is to introduce a bias into the statistics. This bias can become severe for 90 day rolling averages. Here's a quick example of what this looks like:

```
library(RcppRoll)
flow <- rep(c(1:182,183:1), times = 10)
year <- rep(1:10, each = 365)
yours <- c(tapply(flow, year, function(x) roll_mean(x, 90, fill = NA)), recursive = T)
mine <- roll_mean(flow, 90, fill = NA)
tapply(mine, year, min, na.rm = T)
tapply(yours, year, min, na.rm = T)
```

The minimum of the 90 day rolling average should be 23. In the version that mimics your calculations, the minimum is 45.

**Comment by tmills-usgs** [comment]
Hi Jason,

Keep em coming! I am beginning the process of a complete package rewrite of Eflowstats to address the many systematic issues. Please continue to contribute issues if you are able, they are a great help.

I will let you know once I get things really underway on the rewrite

**Comment by tmills-usgs** [comment]
Hello Jason,

Thank you for you posts, they will help me improve the package. As a side not, I did not write this package and have just been serving as a maintainer. However, after delving into the package more deeply it is clear it is going to need a complete refactoring. 

I have started work on refactoring the package, and my primary focus right now is making the code more concise and efficient, along the lines of what you suggested in issue #41 .

Obviously, I do not want issues with the statistics themselves to be carried through and will try to address these as well. However, your issue here appears to be with the original HITHAT statistics (https://www.fort.usgs.gov/sites/default/files/products/publications/21598/21598.pdf). I do not know the rationale for taking the 90 day rolling mean on an annual basis, but that is how the DH and DL groups of statistics were defined. Perhaps @sarchfield or  @wfarmer-usgs could chime in here?

**Comment by sarchfield** [comment]
From what I read from issue #41, the question was raised about why these
calculations are computed separately. The original packages were not meant
to be run in batch mode but rather one site at a time and the original code
was also in Fortran. I think it's a historical artifact as to why the R
code was written in this way.

As for why there are statistics for the 90-day rolling mean, Jason is
correct in that this is more of a question for the authors of the original
program and report. I do know that the statistics that were included in the
original program were because they were found to have some type of
relevance to an ecological community or had been previously used in
ecological flow research. I am guessing a 90-day rolling mean is useful for
seasonal indicators of flow, which would have relevance to the
reproductive/life cycles of ecological communities.

I hope this is helpful,
Stacey

------
Stacey Archfield, Ph.D., Research Hydrologist
National Research Program, U.S. Geological Survey
Mail Stop 430, 12201 Sunrise Valley Drive, Reston, VA  20192
Room 1B318 / p: +1.703.648.5868 / f: +1.703.648.5484
Web: http://profile.usgs.gov/sarch / Skype: staceyarchfield

**Comment by jasonelaw** [comment]
Hi Stacy, I'm not sure whether you addressed the main point of my comment, or perhaps I'm misunderstanding what you were saying. Whether these calculations are done one site at a time or not, the data is being split by year before the rolling statistics are calculated. Which means that it is impossible to have unbiased estimates of these statistics: fully 1/4 of the year is excluded from the 90 day average. The results could vary dramatically depending on the arbitrary year boundary: water year, Gregorian calendar, other calendar systems, etc. If the rolling averages are computed first, the year boundary doesn't affect the results.

The only case where this seems to make sense is when there has been a point disturbance whose effect you are investigating (e.g., dam, etc) where you don't want the data from one period to affect the metrics in another period. This is trivially handled in R by splitting the data at the event before metric calculations.

**Comment by jasonelaw** [comment]
Sorry for mangling your name, @sarchfield!
