### ISSUE TITLE
DH22-24 mis-calculated

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/EflowStats#67]
This issue is pervasive throughout the package when it comes to splitting data on a year or water year mark as @jasonelaw mentioned in issue #61. Periods at the start and end of each year up until a flood event occurs are counted as days between flood events, or rather in the original R code the last event of the year is counted but not the first. This was probably not intended to ignore the first event of the year and is probably a "bug". 

I believe this year cutoff should be removed throughout. For example, in DH22 this causes issues where the start and end of the year are counted as days between flood events for the year, even though there is not a starting or ending event. This can be removed to where the start and end periods are ignored, but it highlights the issue with arbitrarily applying a year cutoff. These edge-of-record issues will still be present when the year cutoff is removed, but will only occur once as apposed to occurring multiple times for every year calculation.

Thoughts? @sarchfield @jasonelaw @wfarmer-usgs

**Comment by jasonelaw** [comment]
I think calculating base metrics before any year splitting is the best approach. My approach has been to pull a dataset that extends beyond the years desired so that rolling stats or other measures that depend on an interval of data don't get any edge effect like this; then I trim the partial year metrics. This would be difficult for time between flood metrics because the interval isn't fixed like the rolling statistics.

**Comment by tmills-usgs** [comment]
I agree, and I will implement this in all functions that calculate metrics on a yearly basis and do not calculate any type of probability.

So for the rolling mean example (#61), I would calculate x-day rolling means for the entire period of record.

Likewise for this example, I would calculate average event durations using the entire period of record.
